kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod                  
spec:                                    
  containers:                      
    - name: c00                     
      image: nginx
      ports:
        - containerPort: 80

  restartPolicy: Never         # Defaults to Always

